# Generated by Django 5.1.1 on 2024-10-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Title',
            new_name='title',
        ),
    ]
