# Generated by Django 5.1.1 on 2024-10-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_title_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='time',
        ),
    ]
