# Generated by Django 5.1.1 on 2024-10-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
